[tool.poetry]
name = "module-s6-homework"
version = "0.1.0"
description = ""
authors = ["Art-eri-ya <gerasartem4@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
faker = "^40.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
